//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentPass { get; set; }
        public string StudentPhone { get; set; }
        public string StudentEmail { get; set; }
        public string GroupCode { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
